services:
  chatbot-api:
    build: .
    container_name: chatbot_server
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .env:/server/.env
      - ./configs/config.yaml:/server/configs/config.yaml
      - ./database:/server/database
      - ./logs:/server/logs
      - ./models:/server/models
    depends_on:
      - redis_db
    entrypoint: bash -c "./bash/run_server.sh"
    networks:
      - chatbot

  redis_db:
    image: redis/redis-stack:edge-arm64
    container_name: containered_chabot_redis
    restart: always
    ports:
      - "6379:6379" # redis database
      - "8001:8001" # redis insight UI
    volumes:
      - ./mount_data/data_chabot_redis:/data
    networks:
      - chatbot

      
networks:
  chatbot:
    name: chatbot
